version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:14
    pull_policy: always
    environment:
      POSTGRES_USER: ${GGAME_DATABASE_USER}
      POSTGRES_PASSWORD: ${GGAME_DATABASE_PASSWORD}
      POSTGRES_DB: ggame_production
      TZ: ${TZ}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
