default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ggame_development
  host: db  # Point to the db service in docker-compose.yml
  username: postgres
  password: password

test:
  <<: *default
  database: ggame_test
  host: db
  username: postgres
  password: password

production:
  <<: *default
  database: ggame_production
  username: <%= ENV['GGAME_DATABASE_USER'] %>
  password: <%= ENV['GGAME_DATABASE_PASSWORD'] %>
  host: <%= ENV['GGAME_DATABASE_HOST'] %>
  port: <%= ENV['GGAME_DATABASE_PORT'] %>
  sslmode: <%= ENV['GGAME_DATABASE_SSLMODE'] %>
